config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'

  get 'password_reset/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/signup',to:'users#new'
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations,only: [:edit]
  resources :password_resets,only: [:new,:create,:edit,:update]
  resources :microposts, only: [:create,:destroy]
  resources :relationships, only:[:create,:destroy]
end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
  <%= simple_form_for @micropost do |f| %>
  <div class="form-group">
    <%= f.input :content,as: :text, input_html: { class: "form-control",rows:10} %>

  </div>
  <%= f.submit "Post", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <span>
    <%= f.input :picture,as: :file %>
  </span>
  <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
      followed
    </strong>
  </a>


</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>