config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'

  get 'password_reset/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/signup',to:'users#new'
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations,only: [:edit]
  resources :password_resets,only: [:new,:create,:edit,:update]
  resources :microposts, only: [:create,:destroy]
  resources :relationships, only:[:create,:destroy]
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type,message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sample App",root_path,class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home",root_path %></li>
        <li><%= link_to "Help",help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users",users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profile',current_user %></li>
            <li><%= link_to 'Settings',edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out",logout_path,method: :delete %></li>

          </ul>

        </li>
        <% else %>
        <li><%= link_to "Log in",login_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>

  </body>
</html>